export enum GradeLevel {
    PRE_K = 'pk',
    KINDERGARTEN = 'k',
    FIRST = '1',
    SECOND = '2',
    THIRD = '3',
    FOURTH = '4',
    FIFTH = '5',
    SIXTH = '6',
    SEVENTH = '7',
    EIGHTH = '8',
    NINTH = '9',
    TENTH = '10',
    ELEVENTH = '11',
    TWELFTH = '12',
    UNKNOWN = '',
}